name: Build Project 
on:
  push:
    branches:
      - main

permissions: 
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build
  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployement.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps: 
      - name: Deploy to Github pages
        id: deployement
        uses: actions/deploy-pages@v4